#!/bin/bash

cd $(dirname $0)
cd ../..

create_config_line() {
    local file=$1

    echo "[type: markdown] content/en/$file \$lang:content/\$lang/$file"
}

create_config() {
    cat << EOF
# PO4A configuration file for the project
# This file was generated by po4a/scripts/create-po4a-config.sh

[options] --keep 0

[po_directory] po4a/po

[po4a_alias:markdown] text opt:"--option markdown" opt:"--option yfm_keys=title,summary" opt:"--addendum-charset=UTF-8" opt:"--localized-charset=UTF-8" opt:"--master-charset=UTF-8"
#[po4a_alias:md] text opt:"markdown" opt:"neverwrap" opt:"yfm_keys Title"

[type: yaml] i18n/en.yml \$lang:i18n/\$lang.yml

# Hugo Configuration files
[type: yaml] config/_default/params.en.yaml \$lang:config/_default/params.\$lang.yaml

EOF
    cd content/en
    
    find . -name '*.md' | sort | while read line
    do
        create_config_line ${line#./}
    done
}

create_config > po4a/po4a.cfg
