#!/bin/bash

cd $(dirname $0)
cd ..

get_base() {
    echo $1 | sed 's/\.md$//g' | sed 's/.en$//'
}

create_config_line() {
    local file=$1
    local base=$(get_base $file)

    echo "[type: markdown] $file \$lang:$base.\$lang.md"
}

create_config() {
    cat << EOF
# PO4A configuration file for the project
# This file was generated by scripts/create-po4a-config.sh

[options] --keep 0

[po_directory] po4a

[po4a_alias:markdown] text opt:"--option markdown" opt:"--option yfm_keys=title,summary" opt:"--addendum-charset=UTF-8" opt:"--localized-charset=UTF-8" opt:"--master-charset=UTF-8"
[po4a_alias:md] text opt:"markdown" opt:"neverwrap" opt:"yfm_keys Title"

[type: yaml] i18n/en.yml \$lang:i18n/\$lang.yml

# [type: markdown] content/_index.en.md $lang:content/_index.$lang.md
# [type: markdown] content/agreements/_index.en.md $lang:content/agreements/_index.$lang.md
# [type: markdown] content/agreements/horses/index.en.md $lang:content/agreements/horses/index.$lang.md

EOF
    find content -name '*.md' | grep -E '(\.??)\.md$' | while read line
    do
        if echo "$line" | grep -E '\.en\.md$' > /dev/null
        then
            create_config_line $line
        elif echo "$line" | grep -E '\.??\.md$' > /dev/null
        then
            continue
        else
            create_config_line $line
        fi
    done
}

create_config
